// Utility functions for downloading documents

export const downloadAsText = (content, filename = 'simplified-document.txt') => {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const downloadAsHTML = (content, filename = 'simplified-document.html') => {
  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Simplified Legal Document - Jurify</title>
      <style>
        body {
          font-family: 'Arial', sans-serif;
          line-height: 1.6;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          color: #333;
        }
        h1 {
          color: #2c3e50;
          border-bottom: 2px solid #3498db;
          padding-bottom: 10px;
        }
        .header {
          background-color: #f8f9fa;
          padding: 20px;
          border-radius: 8px;
          margin-bottom: 30px;
        }
        .content {
          white-space: pre-wrap;
          font-size: 14px;
          line-height: 1.8;
        }
        .footer {
          margin-top: 50px;
          padding-top: 20px;
          border-top: 1px solid #e0e0e0;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>⚖️ Simplified Legal Document</h1>
        <p><strong>Generated by Jurify</strong> - AI-Powered Legal Document Simplification</p>
        <p><em>Date: ${new Date().toLocaleDateString()}</em></p>
      </div>
      <div class="content">${escapeHtml(content)}</div>
      <div class="footer">
        <p>⚠️ This document is a simplified version for easier understanding.</p>
        <p>It is not intended as legal advice. Please consult with a legal professional for official guidance.</p>
        <p>&copy; 2025 Jurify - Demystifying Legal Documents</p>
      </div>
    </body>
    </html>
  `;
  
  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const downloadAsJSON = (originalContent, simplifiedContent, clauses, filename = 'document-analysis.json') => {
  const data = {
    timestamp: new Date().toISOString(),
    source: 'Jurify - AI Legal Document Simplification',
    documents: {
      original: originalContent,
      simplified: simplifiedContent
    },
    clauseAnalysis: clauses,
    metadata: {
      generatedAt: new Date().toLocaleDateString(),
      version: '1.0.0'
    }
  };
  
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// Helper function to escape HTML
const escapeHtml = (text) => {
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
};